spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener?options=-c%20TimeZone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      #ddl-auto: validate
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    connect-retries: 10
    connect-retry-delay: 5000